name: fun time
markdown: redcarpet
highlighter: pygments # or rouge or null
timezone: America/New_York
exclude: ["node_modules", "gulpfile.js", "package.json"]



column-heading-one: Jonah

answer1-100: The one who told Jonah to go preach repentence to the Ninevites.
question1-100: Who is the Lord

answer1-200: This city would be destroyed if they did not repent of their wickedness
question1-200: What is Ninevah?

answer1-300: This is how the men on the boat determined who was the cause of the storm
question1-300: What is casting lots

answer1-400: This is the city that Jonah fled to instead of obeying God and going to Ninevah
question1-400: What is Tarshish?

########Column Heading Two#########
column-heading-two: Simon & the sinful woman

answer2-100: This was Simon's Job / Title
question2-100: What is a pharisee

answer2-200: The woman cleaned jesus's feet with these things
question2-200: What are her tears, hair, perfume

answer2-300: Simon refused to offer two customary greetings to Jesus
question2-300: kiss of greeting & annointing head with olive oil

answer2-400: Jesus gives this illustration while at dinner regarding forgiveness.
question2-400: Money lent to two people (50 denari & 500 denari) Both were forgiven, who loved forgiveness the most?

########Column Heading three#########
column-heading-three: The Rich man and Lazarus

answer3-100: What lazarus desired to be fed with form the rich man's table
question3-100: Whatever fell form the rich man's table. 

answer3-200: The rich man's first request of Father Abraham while he was in hell
question3-200: What is to send Lazarus to dip the end of his finger in water and cool my tongue

answer3-300: The reasons why this parable was hard for the parisees to believe
question3-300: The pharisees thought that if you were rich you had God's blessing and favor. They also thought that if you were poor or sick you were sinful and did not have God's favor

answer3-400: Father Abraham's response to the rich man after he asks Lazarus to go back from the dead and warn his family of hell.
question3-400: They have Moses and the Prophets; let them hear them. (If you do not have faith, not even someone coming back from the dead will convince a hardened heart)

########Column Heading four#########
column-heading-four: King Solomon

answer4-100: King solomon was the richest man in all the world. He was also this
question4-100: Who is the wiset man who ever lived. 

answer4-200: This is the Book King Solomon records his wisdom, mistakes and achievements.
question4-200: What is the book of Ecclesiastes

answer4-300: God offered Solomon anything he wanted and he chose this
question4-300: What is wisdom

answer4-400: This sums up Solomon's wisdom and what he learned throughout his life
question4-400: All is vanity and chasing after the wind. Fear the lord & keep his commandments; everyone will eventually die and all the deeds of man are vanity (useless) without God.

########Column Heading five#########
column-heading-five: Jesus & the Samaritan Woman

answer5-100: This is why the Samaritan woman was shocked that jesus asked her for a drink of water 
question5-100: What is that he was a Jew and she was a Samaritan 

answer5-200: After hearing the good news of the Gospel the Samaritan woman did this
question5-200: What is went into town and told her friends about Jesus

answer5-300: This is what Jesus meant by "living water"
question5-300: What is eternal life

answer5-400: Jesus explains that a time is coming when true worshipers will worship in these two ways
question5-400: What are Spirit and Truth



